var Users = document.getElementById('Users');
var Users_toggle = document.getElementById('Users_toggle')
var Products = document.getElementById('Products_box');
Products.style.display = 'none';
var Products_toggle = document.getElementById('Products_toggle');
var Popular_Products_toggle = document.getElementById('Popular_Products_toggle');
var Main_Popular_Products_toggle = document.getElementById('Main_Popular_Products_toggle');
var Message_toggle = document.getElementById('Message_toggle');
var Message = document.getElementById('Message_container');
Message.style.display = 'none';
var Blog = document.getElementById('Blog_container');
var Blog_toggle = document.getElementById('Blog_toggle');
Blog.style.display = 'none';
var Popular_Products_toggle = document.getElementById('Popular_Products_toggle');
var Popular_product = document.getElementById('Popular_product_box');
Popular_product.style.display = 'none';
var Liked_product = document.getElementById('Liked_container');
Liked_product.style.display = 'none';
var Liked_toggle = document.getElementById('Liked_toggle');
var Cart_product = document.getElementById('Cart_container');
Cart_product.style.display = 'none';
var Cart_toggle = document.getElementById("Add_to_card_toggle");
var Most_popular = document.getElementById('Most_popular_container');
Most_popular.style.display = 'none';
var Most_popular_toggle = document.getElementById('Main_Popular_Products_toggle');
Users_toggle.addEventListener('click', () => {
    Users.style.display = 'flex';
    Products.style.display = 'none';
    Message.style.display = 'none';
    Blog.style.display = 'none';
    Popular_product.style.display = 'none';
    Liked_product.style.display = 'none';
    Cart_product.style.display = 'none';
    Most_popular.style.display = 'none';
})
Products_toggle.addEventListener('click', () => {
    Users.style.display = 'none';
    Products.style.display = 'flex';
    Message.style.display = 'none';
    Blog.style.display = 'none';
    Popular_product.style.display = 'none';
    Liked_product.style.display = 'none';
    Cart_product.style.display = 'none';
    Most_popular.style.display = 'none';
})
Message_toggle.addEventListener('click',()=> {
    Message.style.display = 'flex';
    Users.style.display = 'none';
    Products.style.display = 'none';
    Blog.style.display = 'none';
    Popular_product.style.display = 'none';
    Liked_product.style.display = 'none';
    Cart_product.style.display = 'none';
    Most_popular.style.display = 'none';
})
Blog_toggle.addEventListener('click',()=> {
    Users.style.display = 'none';
    Products.style.display = 'none';
    Message.style.display = 'none';
    Blog.style.display = 'flex';
    Popular_product.style.display = 'none';
    Liked_product.style.display = 'none';
    Cart_product.style.display = 'none';
    Most_popular.style.display = 'none';
})
Popular_Products_toggle.addEventListener('click',()=> {
    Users.style.display = 'none';
    Products.style.display = 'none';
    Message.style.display = 'none';
    Blog.style.display = 'none';
    Popular_product.style.display = 'flex';
    Liked_product.style.display = 'none';
    Cart_product.style.display = 'none';
    Most_popular.style.display = 'none';
})
Liked_toggle.addEventListener('click',()=> {
    Liked_product.style.display = 'flex'; 
    Users.style.display = 'none';
    Products.style.display = 'none';
    Message.style.display = 'none';
    Blog.style.display = 'none';
    Popular_product.style.display = 'none';
    Cart_product.style.display = 'none';
    Most_popular.style.display = 'none';
})
Cart_toggle.addEventListener('click',()=> {
    Liked_product.style.display = 'none'; 
    Users.style.display = 'none';
    Products.style.display = 'none';
    Message.style.display = 'none';
    Blog.style.display = 'none';
    Popular_product.style.display = 'none';
    Cart_product.style.display = 'flex';
    Most_popular.style.display = 'none';
})
Most_popular_toggle.addEventListener('click',()=> {
    Liked_product.style.display = 'none'; 
    Users.style.display = 'none';
    Products.style.display = 'none';
    Message.style.display = 'none';
    Blog.style.display = 'none';
    Popular_product.style.display = 'none';
    Cart_product.style.display = 'none';
    Most_popular.style.display = 'flex';
})